main: net.lotrcraft.wheatheal.WHMain
authors: [numenorean95, EdTheLoon]
name: WheatHeal
version: 0.4
website: http://lotrcraft.net/plugins/wheatheal

commands:
    wheatheal:
        description: Reload the configuration file
        aliases: wh
        usage: |
            /wheatheal reload - Reload the configuration file

permissions:
    wheatheal.*:
        description: Gives access to all WheatHeal permissions
        default: false
        children:
            WheatHeal.commands.reload: true
    wheatheal.commands.reload:
        description: Allows user to reload the configuration file
        default: op
