main: net.lotrcraft.wheatheal.WHMain
author: numenorean95 (Some updates by EdTheLoon)
name: WheatHeal
version: 0.2

commands:
    wheatheal:
        description: Reload the configuration file
        usage: |
            /wheatheal reload - Reload the configuration file

permissions:
    wheatheal.*:
        description: Gives access to all WheatHeal permissions
        default: false
        children:
            WheatHeal.commands.reload: true
    wheatheal.commands.reload:
        description: Allows user to reload the configuration file
        default: op
