main: net.lotrcraft.wheatheal.WHMain
author: Numenorean95
authors: [EdTheLoon, Lathanael]
name: WheatHeal
version: 1.0
website: http://lotrcraft.net/plugins/wheatheal

commands:
    wheatheal:
        description: Reload the configuration file
        aliases: wh
        usage: |
            /wheatheal reload - Reload the configuration file

permissions:
    wheatheal.*:
        description: Gives access to all WheatHeal permissions
        default: false
        children:
            WheatHeal.commands.reload: true
            WheatHeal.heal: true
    wheatheal.commands.reload:
        description: Allows user to reload the configuration file
        default: op
    wheatheal.heal:
        description: Allows user to heal another player
        default: op
